target:
- Age
continuous_cols:
- CXCL9_log
- CCL11_log
- IL27_log
- IL5_log
- CSF1_log
- CCL2_log
- IL1B_log
- IL6_log
- GCSF_log
- CXCL10_log
- VEGFA_log
- TNF_log
- PDGFB_log
- IL8_log
- PDGFA_log
- IL12Bp40_log
- IL15_log
- CXCL1_log
- CCL4_log
- IFNA2_log
- IL13_log
- FLT3L_log
- CD40LG_log
- CCL22_log
categorical_cols: []
date_columns: []
encode_date_columns: true
validation_split: 0.25
continuous_feature_transform: yeo-johnson
normalize_continuous_features: true
quantile_noise: 0
num_workers: 0
pin_memory: true
handle_unknown_categories: true
handle_missing_values: true
task: regression
head: LinearHead
head_config:
  layers: ''
  activation: ReLU
  dropout: 0.23377289048411876
  use_batch_norm: false
  initialization: xavier
embedding_dims: null
embedding_dropout: 0.0
batch_norm_continuous_input: true
learning_rate: 0.029204372085555506
loss: L1Loss
metrics:
- mean_absolute_error
- pearson_corrcoef
metrics_prob_input:
- false
- false
metrics_params:
- {}
- {}
target_range: null
virtual_batch_size: 256
seed: 1984
_module_src: models.danet
_model_name: DANetModel
_backbone_name: DANetBackbone
_config_name: DANetConfig
n_layers: 28
abstlay_dim_1: 8
abstlay_dim_2: 64
k: 2
dropout_rate: 0.2320482225690916
block_activation: LeakyReLU
batch_size: 1024
data_aware_init_batch_size: 2000
fast_dev_run: false
max_epochs: 256
min_epochs: 1
max_time: null
accelerator: auto
devices: -1
devices_list: null
accumulate_grad_batches: 1
auto_lr_find: false
auto_select_gpus: true
check_val_every_n_epoch: 1
gradient_clip_val: 0.0
overfit_batches: 0.0
deterministic: false
profiler: null
early_stopping: valid_loss
early_stopping_min_delta: 0.001
early_stopping_mode: min
early_stopping_patience: 20
early_stopping_kwargs: {}
checkpoints: valid_loss
checkpoints_path: D:/YandexDisk/Work/bbd/immunology/003_EpImAge/imp_source(imm)_method(knn)_params(5)/no_harm/mrmr_100/EpImAge/pytorch_tabular
checkpoints_every_n_epochs: 1
checkpoints_name: null
checkpoints_mode: min
checkpoints_save_top_k: 1
checkpoints_kwargs: {}
load_best: true
track_grad_norm: -1
progress_bar: none
precision: 32
trainer_kwargs: {}
optimizer: Adam
optimizer_params:
  weight_decay: 2.149173764897728e-08
lr_scheduler: ReduceLROnPlateau
lr_scheduler_params:
  mode: min
  factor: 0.7071915700100401
  patience: 10
  threshold: 0.0001
lr_scheduler_monitor_metric: valid_loss
enable_checkpointing: true
